#To-Do:
#Add some way of adding crafting recipes to the config in-game

CustomRecipes: 
 
  #To add recipes you need to change how many recipes there are.
  NumberOfRecipes: 2
  
  #Add a new recipe in this fashion
  0: 
    #0 is the top left 
    #null means there is nothing in the 
    0: "null"
    #1 is the top middle 
    1: "null"
    #2 is the top right 
    2: "null"
    #3 is the middle left 
    3: "null"
    #4 is the center 
    4: "null"
    #5 is the middle right 
    5: "ARROW"
    #6 is the bottom left  
    6: "null"
    #7 is the bottom middle 
    7: "null"
    #8 is the bottom right 
    8: "null"
    
    #9 is the output
    9: "SADDLE"

  1: 
    #0 is the top left 
    0: "null"
    #1 is the top middle 
    1: "null"
    #2 is the top right 
    2: "null"
    #3 is the middle left 
    3: "null"
    #4 is the center 
    4: "null"
    #5 is the middle right 
    5: "APPLE"
    #6 is the bottom left  
    6: "null"
    #7 is the bottom middle 
    7: "null"
    #8 is the bottom right 
    8: "null"
    
    #9 is the output
    9: "ANVIL"
    
