# Available color codes:
# &0 Black        &6 Gold       &c Red
# &1 Dark Blue    &7 Gray       &d Light Purple
# &2 Dark Green   &8 Dark Gray  &e Yellow
# &3 Dark Aqua    &9 Blue       &f White
# &4 Dark Red     &a Green     
# &5 Dark Purple  &b Aqua

# Available formatting codes:
# &k Obfuscated   &m Strikethrough
# &l Bold         &o Italic
# &n Underline    &r Reset

#To-Do:
#Add some way of adding crafting recipes to the config in-game

CustomRecipes: 
 
  #To add recipes you need to keep how many recipes there are.
  NumberOfRecipes: 2
  
  #Add a new recipe in this fashion
  0: 
    #Slot 0 is the top left slot
    #null means there is nothing in the slot
    Slot0: null
    #Slot 1 is the top middle slot
    Slot1: null
    #Slot 2 is the top right slot
    Slot2: null
    #Slot 3 is the middle left slot
    Slot3: 
    #Slot 4 is the center slot
    Slot4:
    #Slot 5 is the middle right slot
    Slot5:
    #Slot 6 is the bottom left slot 
    Slot6: 
    #Slot 7 is the bottom middle slot
    Slot7: 
    #Slot 8 is the bottom right slot
    Slot8: 
    
    #This is the output
    Output: 

  1: 
    #Slot 0 is the top left slot
    Slot0: 
    #Slot 1 is the top middle slot
    Slot1:
    #Slot 2 is the top right slot
    Slot2:
    #Slot 3 is the middle left slot
    Slot3: 
    #Slot 4 is the center slot
    Slot4:
    #Slot 5 is the middle right slot
    Slot5:
    #Slot 6 is the bottom left slot 
    Slot6: 
    #Slot 7 is the bottom middle slot
    Slot7: 
    #Slot 8 is the bottom right slot
    Slot8: 
    
    #This is the output
    Output: 
    
